Add Keycloak to docs and fix wrong links
vshn/appcat-user-docs pull request #102
Opened 2024-05-14 11:52 UTC by TheBigLee

2024-05-14 11:54 UTC, wejdross approved these changes

2024-05-14 11:59 UTC, zugao requested changes

2024-05-14 11:59 UTC, zugao commented on docs/modules/ROOT/pages/index.adoc
> +|xref:object-storage/create.adoc[Create] and xref:object-storage/usage.adoc.adoc[use]
`usage.adoc.adoc` ?

Seems wrong

2024-05-15 12:01 UTC, Kidswiss approved these changes

2024-05-21 10:47 UTC, merged