Add docs for extensions
vshn/appcat-user-docs pull request #71
Opened 2023-07-12 11:09 UTC by Kidswiss

2023-07-12 11:28 UTC, lieneluksika approved these changes

2023-07-12 15:44 UTC, tobru requested changes

2023-07-12 15:44 UTC, tobru commented on docs/modules/ROOT/pages/vshn-managed/postgresql/extensions.adoc
> +PostgreSQL supports many different extenions, such as PostGIS and TimescaleDB.
```suggestion
PostgreSQL supports many different extensions, such as https://postgis.net/[PostGIS^] and https://www.timescale.com/[TimescaleDB^].
```

2023-07-12 15:44 UTC, tobru commented on docs/modules/ROOT/pages/vshn-managed/postgresql/extensions.adoc
> +== Enable extenions
```suggestion
== Enable PostgreSQL Extensions
```

2023-07-12 15:44 UTC, tobru commented on docs/modules/ROOT/pages/vshn-managed/postgresql/extensions.adoc
> +To enable an extension add the following to your instance:
```suggestion
To enable an extension, add the following configuration to your instance:
```

2023-07-12 15:44 UTC, tobru commented on docs/modules/ROOT/pages/vshn-managed/postgresql/extensions.adoc
> +After applying the change AppCat will ensure that the extension is available after a short while.
```suggestion
After applying the change, AppCat will ensure that the extension is available after a short while.
```

2023-07-12 15:44 UTC, tobru commented on docs/modules/ROOT/pages/vshn-managed/postgresql/extensions.adoc
> +Depending on your https://docs.appcat.ch/vshn-managed/postgresql/update-strategy.html[Instance Update Strategy] it's possible that the instance will restart immediately.
```suggestion
Depending on your https://docs.appcat.ch/vshn-managed/postgresql/update-strategy.html[Instance Update Strategy], it's possible that the instance will restart immediately.
```

2023-07-13 06:52 UTC, tobru commented on docs/modules/ROOT/pages/vshn-managed/postgresql/extensions.adoc
> += Add extensions to the instance
```suggestion
= PostgreSQL Extensions
```

As the title appears on the navigation, I'd pick a shorter title here.

2023-07-13 06:53 UTC, tobru commented on docs/modules/ROOT/pages/vshn-managed/postgresql/extensions.adoc
> +PostgreSQL supports many different extensions, such as https://postgis.net/[PostGIS^] and https://www.timescale.com/[TimescaleDB^].
```suggestion
PostgreSQL supports many different extensions, such as https://postgis.net/[PostGIS^] or https://www.timescale.com/[TimescaleDB^].
```

2023-07-13 06:53 UTC, tobru commented on docs/modules/ROOT/pages/vshn-managed/postgresql/extensions.adoc
> +For a list of all available extensions please https://stackgres.io/doc/latest/intro/extensions/[consult this page].
```suggestion
For a list of all available extensions please https://stackgres.io/doc/latest/intro/extensions/[consult this page^].
```

Let's open external links in a new tab

2023-07-13 06:54 UTC, tobru commented on docs/modules/ROOT/pages/vshn-managed/postgresql/extensions.adoc
> +
```suggestion
        - name: ltree <1>
----

<1> Name of the extension as found on the "Name" column at https://stackgres.io/doc/latest/intro/extensions/[the official listing^]. Add more extensions to the list as needed.
```

2023-07-13 09:27 UTC, merged